### ISSUE TITLE
Ignore sensitive data in the project

### ISSUE THREAD

**Issue by HlibBondarev** [project-studying-dotnet/Streetcode-Admin#15]

**Comment by HlibBondarev** [comment]
Create Manual for resolving this task.

**Comment by HlibBondarev** [comment]
**Manual**

1) Add UserSecrets NuGet Package (Microsoft.Extensions.Configuration.UserSecrets) to Project if it is not already installed.

2) Open User Secrets file.
Right click on your project and select the context menu option Manage User Secrets (see pic_1) and add your ConnectionString for local DB.  For me it is (see pic_2):
"ConnectionStrings": {
    "DefaultConnection": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=StreetcodeDb;Integrated Security=True;Connect Timeout=30;"
}

3) Register User Secrets at Start-Up.
For it - Add code (see pic_3) to ConfigureCustom() method in ConfigurationBuilderExtensions class:
.AddUserSecrets<Program>(); // For your local Dev environment only, this won't exist within the Production environment
 
**Conclusion**
You won’t see the created file named secrets.json inside the solution explorer as it’s saved within your roaming data. 
The physical path to your secrets.json file is not included in your code check-in and and is not tracked by Git.
**_

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/a032a49f-a8ed-4018-8111-812bfca9cfb2)



![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/f6391492-b320-46dd-8276-b26d1de381a4)



![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/56700347/4cfc0a32-13ea-4426-b947-4f44feeb20b4)

_.**

**Comment by MrVenik** [comment]
maybe close this issue ?
