### ISSUE TITLE
Admin/History map

### ISSUE THREAD

**Issue by mehalyna** [project-studying-dotnet/Streetcode-Admin#2]
**As a** Admin **I want to** manage Admin/History Map

![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/de489a7f-0307-4377-bb75-a8a97827f038)

### Acceptance Criteria

1. Admin can add records about the location of physical street code:
-can be added via a dropdown
-can be added via a selection of specific locations on a map
2. Admin can delete records
3. Number of physical street code should be unique per one street code
![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/c1e84851-e47a-4bcb-baec-a4751e500168)

**Comment by HlibBondarev** [comment]
**Development tasks**
1. Can be used one DTO - StreetcodeToponymDTO for creating and deleting, should contain: StreetcodeId and ToponymId
2. Endpoints
2.1. Create - which would receive StreetcodeToponymDTO and then - create StreetcodeToponym entitie.
2.2. Delete - which would receive StreetcodeToponymDTO - StreetcodeToponym entitie
Mediator Handlers
3.1. CreateStreetcodeToponymHandler and CreateStreetcodeToponymCommand
3.2. DeleteStreetcodeToponymHandler and DeleteStreetcodeToponymCommand
Tests
4.1. CreateStreetcodeToponymHandler tests
4.2. DeleteStreetcodeToponymHandler tests


**Vertical slice** (not block others after creating StreetcodeToponymDTO p.1.)

1. StreetcodeToponymDTO for creating and deleting, should contain: StreetcodeId and ToponymId

Create
2.1. Create endpoint
2.2. CreateStreetcodeToponymHandler and CreateStreetcodeToponymCommand
2.3. CreateStreetcodeToponymHandler tests

Delete
3.1. Delete endpoint
3.2. DeleteStreetcodeToponymHandler and DeleteStreetcodeToponymCommand
3.3. DeleteStreetcodeToponymHandler tests

**Comment by HlibBondarev** [comment]
Development tasks
1. Can be used one DTO - StreetcodeToponymDTO for creating and deleting, should contain: StreetcodeId and ToponymId
2. Endpoints
2.1. Create - which would receive StreetcodeToponymDTO and then - create StreetcodeToponym entitie.
2.2. Delete - which would receive StreetcodeToponymDTO - StreetcodeToponym entitie
Mediator Handlers
3.1. CreateStreetcodeToponymHandler and CreateStreetcodeToponymCommand
3.2. DeleteStreetcodeToponymHandler and DeleteStreetcodeToponymCommand
Tests
4.1. CreateStreetcodeToponymHandler tests
4.2. DeleteStreetcodeToponymHandler tests



Vertical slice (not block others after creating StreetcodeToponymDTO p.1.)

1. StreetcodeToponymDTO for creating and deleting, should contain: StreetcodeId and ToponymId

Create
2.1. Create endpoint
2.2. CreateStreetcodeToponymHandler and CreateStreetcodeToponymCommand
2.3. CreateStreetcodeToponymHandler tests

Delete
3.1. Delete endpoint
3.2. DeleteStreetcodeToponymHandler and DeleteStreetcodeToponymCommand
3.3. DeleteStreetcodeToponymHandler tests

**Comment by MrVenik** [comment]
Create validation for uniqunes of streetcode index per toponym
