### ISSUE TITLE
BugFix: Change this condition so that it does not always evaluate to 'False'. Some code paths are unreachable in GetAllWithTeamMembersHandler

### ISSUE THREAD

**Issue by SvyatoS1** [project-studying-dotnet/Streetcode-Admin#26]
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=ita-social-projects_StreetCode&open=AYqQqzKoVKJ35N4Ga8xU

**Comment by MrVenik** [comment]
Not related to our project.
