### ISSUE TITLE
BugFix: Change this condition so that it does not always evaluate to 'True'. Some code paths are unreachable in GetPageOfStreetcodesMainPageHandler

### ISSUE THREAD

**Issue by SvyatoS1** [project-studying-dotnet/Streetcode-Admin#47]
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=ita-social-projects_StreetCode&open=AYuCl4jA-BEeFfDiQf5K

**Comment by MrVenik** [comment]
Are you sure that this bug is related to our project?

**Comment by MrVenik** [comment]
Not related to our project.
