### ISSUE TITLE
Admin/Interesting facts block

### ISSUE THREAD

**Issue by mehalyna** [project-studying-dotnet/Streetcode-Admin#5]
Admin/Interesting facts block

![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/af73cb44-b366-405d-a3b6-e37cfeb5544d)

### Acceptance Criteria

1. Admin can add a new fact via "+" button
1.1. System opens a modal window where an Admin can add an image, title and text. All items are mandatory
1.2. Admin can add no more than 600 symbols to main text field and 68 symbols to title. Counter for "symbols left" is displayed
1.3. Admin can add a description for an attached photo. This is not a mandatory field, limited up to 200 symbols.
2. Admin can edit existing facts via "pencil" icon
3. Admin can delete existing facts via "trash" icon
4. All facts are displayed as small blocks with titles on it
5. Admin can reorder facts 
![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/92371c12-0e06-47bc-a6d4-0c072501584b)

**Comment by MrVenik** [comment]
## Development tasks
1. DTOs
1.1. CreateFactDTO - dto for creating fact, should contain: title, fact content and ImageFileBaseCreateDTO
1.2. UpdateFactDTO - dto for updating fact, should contain: id, title, fact content and ImageFileBaseCreateDTO all fields is optional, except id
1.3. DeleteFactDTO (?) - it is only id - so maybe this would be redundant
2. Endpoints
2.1. Create - which would receive CreateFactDTO and then - create image base on ImageFileBaseCreateDTO, then - create fact, where image id is received through create image command
2.2. Update -which would receive UpdateFactDTO and then - update image (delete old, create new) if any image is presented, then - update fact
2.2. Delete - which would receive fact id (or DTO) - then cascadly delete fact and related to this fact entities
3. Mediator Handlers
3.1. CreateFactHandler and CreateFactCommand 
3.2. UpdateFactHandler and UpdateFactCommand
3.3. DeleteFactHandler and DeleteFactCommand
4. Tests
4.1. CreateFactHandler tests
4.2. UpdateFactHandler tests
4.3. DeleteFactHandler tests
