### ISSUE TITLE
Admin/Art gallery block

### ISSUE THREAD

**Issue by mehalyna** [project-studying-dotnet/Streetcode-Admin#7]
**Admin/Art gallery block**

![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/c4cb2b06-45df-44b3-ad7c-efb28327e4c8)

### Acceptance Criteria

1. Admin can upload images
2. Images are displayed in the same way like it is working on user-facing StreetCode 
3. ~~Admin can reorder images~~ will not be implemented in MVP
4. Admin can add title (up to 150 symbols) and description (up to 400 symbols) to images, non-mandatory fields
5. Admin can delete images
![image](https://github.com/ita-social-projects/Streetcode-Admin/assets/45690640/4fa98b5b-4ea1-49cd-8325-f4e4bb0d28ff)

**Comment by VictorLuchyk** [comment]
### Development tasks

**1. Image Upload:**

- Implement MediatR handler for handling image uploads.

- Implement validation for supported file formats (e.g., JPEG, PNG) and maximum file size

-  If image preprocessing (resizing) is needed, implement logic.


**2. Image Display:**

- Implement pagination logic

-  Implement queries to retrieve uploaded images and associated metadata from the database.

**3. Add Descriptions:**

- Implement validation for character length limits (150 for title, 400 for description).

- Update image DTO to include  description field.

**4. Write unit tests for MediatR handler.**
