### ISSUE TITLE
Investigate: FluentValidation implementation

### ISSUE THREAD

**Issue by MrVenik** [project-studying-dotnet/Streetcode-Admin#85]
In order to get acquainted with FluValid it is worth to make next actions:

- Google -> FluentValidation in asp.net core
- generally get acquainted with a couple of articles like:
  https://www.youtube.com/watch?v=Nw5iLDxhEAA
  https://ravindradevrani.medium.com/fluent-validation-in-net-core-8-0-c748da274204
  https://dev.to/osempu/data-validation-with-fluent-validation-for-asp-net-core-92c
  https://codewithmukesh.com/blog/fluent-validation-aspnet-core/
  Or other articles from web results
  This stage should create a basic understanding of what is FluValid, its purposes, how to use.
- breafly investigate tech documentation (take to account all chapters)
  https://docs.fluentvalidation.net/en/latest/aspnet.html
- Create some example in test project (it worth to have complex class to validate - class that has property of some customn type(another class + `List<another class>`))
- Take a real task in order to create FluValid functionality

Example: (in process)
In Startup.cs (Program.cs) in `ConfigureServices(IServiceCollection services)` we add extension method that configure some project  settings (in example case it is Application project - AddAplication() respectively)

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/f70b190c-7a15-43df-8dfb-d59f6cabc36b)
In  ext method` AddAplication()` in constructor we initialize all necesary services by caling private methods

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/f89a77ed-7018-42d8-9c64-1f9b4b84c6e4)

As we will valid all necesary models in mediatr we **add special service** that define how our valid behaviour will act.

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/c1c6cb7e-2c19-4852-a76d-a32b74233fe9)

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/b9efff00-a812-4a01-b6af-a1819d0a43b7)

**Comment by MrVenik** [comment]
https://www.youtube.com/watch?v=AYrmu9_RFnM

**Comment by MishaPolishchuk** [comment]
![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/d7bae803-0922-4250-bf18-09a462666f8c)


You can read breafly about  validation behaviour pipeline here:
https://codewithmukesh.com/blog/mediatr-pipeline-behaviour/

**Comment by MishaPolishchuk** [comment]
Actually validation functionallity:
- In project where validation will have part add class for future validation  extension methods
![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/9a922147-419f-4f31-84b5-2c3569c26582)

- In Mediatr.YourTypesCollection directory create class to provide validations: 
![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/ca3c1754-1539-43fb-b688-18f2b8b73e0d)

**Comment by MishaPolishchuk** [comment]
We have to valid LoginModel in AccountController wich flows further to LoginUserCommand


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/6478f94a-26b1-487e-b298-bffadda56d1b)

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/fdb7208f-f174-4dd5-bf99-5c5f22b22d3b)
During execution (creating LoginUserCommandHandler) handling LoginUserCommand our validator (LoginUserCommandValidator) will intercept the reguest model (LoginUserCommand) and validation of the LoginModel(uwhich is incapsulated in LoginUserCommand ) will take place

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/5cd5bd0c-c298-4812-bf2e-5b51d04a0cec)


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/6f663138-8d4b-4463-8bfc-6788e1a72750)

**Comment by MishaPolishchuk** [comment]
Now in order to provide additional(more complex) validation related to some necessary checks we create extension methods for property with data of wich we will provide such additional validation


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/9d8a513c-6a6f-4b08-84dd-f3bf8e036b04)


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/138890339/07d30635-5426-4fd4-87be-e98fb360e2bd)

**Comment by MishaPolishchuk** [comment]
Фсьоооо!, щоб мені таке хто тоді написав))
