### ISSUE TITLE
Investigate: Middlewares

### ISSUE THREAD

**Issue by MishaPolishchuk** [project-studying-dotnet/Streetcode-Admin#87]

**Comment by MrVenik** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0

**Comment by SvyatoS1** [comment]
# Middlewares manual
 - ## Introduction
    - Middleware in ASP.NET Core is software components that are assembled into an application pipeline to handle requests and responses. Middleware can perform various tasks such as authentication, logging, error handling, and more.
 - ## Source links
     - Here is the bunch of links that will help you understand the topic:
     -  **Microsoft Documentation:** 
      https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0
     - **Articles:**
     https://www.c-sharpcorner.com/article/overview-of-middleware-in-asp-net-core/
     https://dev.to/andytechdev/aspnet-core-middleware-working-with-global-exception-handling-3hi0
     - **Youtube**
     https://www.youtube.com/watch?v=TqCshF0o0nE&ab_channel=ShawnWildermuth
     https://www.youtube.com/watch?v=H3EbflpXVmo&ab_channel=MilanJovanovi%C4%87
 - ## Example
     As an example will be review a ApiRequestResponseMiddleware.cs file to fully understand the topic of middlewares. [Link](https://github.com/ita-social-projects/StreetCode/blob/master/Streetcode/Streetcode.BLL/Middleware/ApiRequestResponseMiddleware.cs) to the repo.
### 1. Middleware setup


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/7af51f4b-27a1-468a-b3bd-428b6a3bcd17)

 - RequestDelegate _next: Represents the next middleware component in the request processing pipeline.
 - ILogger<ApiRequestResponseMiddleware> _loggerService: Provides logging capabilities for the middleware.
 - RequestResponseMiddlewareOptions _options: Configuration options for the middleware.
 - And constructor initializes the middleware with dependencies above.
### 2. InvokeAsync Method
 

![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/4ffca7cc-1553-4490-bbcb-21ba4c5fcd07)

- Entry point for the middleware execution.
- Captures incoming HTTP requests and outgoing HTTP responses for logging.
- Invokes the next middleware component in the pipeline.
- Logs request details and response details, or logs an exception if one occurs during request processing.
### 3. FormatResponseAsync Method


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/0476823e-75bf-4045-96ec-4b707decdcdb)
- Formats the outgoing HTTP response for logging.
- Captures the response body, applies filtering if necessary, and copies the modified body back to the response stream.
### 4. GetRequestAsTextAsync Method


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/40a0ceaa-90d0-4e78-912c-74cc0518c229)

- Reads the incoming HTTP request body as text.
- Enables buffering to allow the stream to be read multiple times.
- Applies filtering to the request body based on configuration options.


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/e6719e2a-8867-45e3-a39b-7084c417ef71)

- Reads the outgoing HTTP response body as text.
- Seeks to the beginning of the response stream, reads the content, and seeks back to the beginning for further processing.
- Applies filtering to the response body based on configuration options.
### 5. GetFilteredBody Method


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/b53ccc93-44c0-4af6-bae8-80b7376f0320)

- Filters and formats the request or response body based on its content.
- Parses the JSON content and truncates properties if necessary.
- Logs any exceptions encountered during parsing or filtering.
### 6. TruncateProperties Method


![Image](https://github.com/project-studying-dotnet/Streetcode-Admin/assets/107581459/1198a2c3-a07c-480d-9783-8162b31c892b)

- Truncates properties within a JSON object or array based on configuration options.
- Removes properties to ignore and truncates values that exceed the maximum response length.

 - ## Summary
 - The ApiRequestResponseMiddleware intercepts HTTP requests and responses, logs details, and filters request/response bodies based on configuration options. It enhances observability and aids in troubleshooting issues related to request/response data.
